repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff-lint
        entry: uv run ruff check --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: pytest
        name: pytest
        entry: uv run pytest -sv
        language: system
        pass_filenames: false
        always_run: true
      - id: check-version
        name: check-version-bump
        entry: uv run python .dev/check_version.py
        language: system
        pass_filenames: false
        always_run: true
